### PR TITLE
Gradle CI with Github Actions

### PR DESCRIPTION
**Pull request by vinopm**

### CODE REVIEW

**Comment by johnnonweiler** [comment]
This looks good, and I don't know why the build is failing.  I did a bit of digging with GitHub search, and found this example of someone else doing a gradle build which seems to be working:
https://github.com/MikhailMe/master-thesis/runs/641274505
This is his configuration - I don't know what the significant difference is:
https://github.com/MikhailMe/master-thesis/blob/master/.github/workflows/gradle.yml

Also, these configurations seemed to produce some successful builds:
https://github.com/Owain94/OpenOSRS-RL-hub/blob/master/.github/workflows/gradle.yml
https://github.com/jaypwns0/plugins2/blob/master/.github/workflows/gradle.yml

**Comment by vinopm** [comment]
Thanks @johnnonweiler , i'll take a look at the links which you have provided

**Comment by vinopm** [comment]
@johnnonweiler please review when you have time

**Comment by johnnonweiler** [comment]
Looks good!

**Comment by sam-brett** [comment]
All good from my point of view. Welcome aboard!

**Pull request merged**
